### ISSUE TITLE
Guidelines not visible anymore in the last update

### ISSUE THREAD

**Issue by blablubbabc** [pharring/EditorGuidelines#111]
I noticed that the guidelines were no longer rendering. I think VisualStudio automatically installed some update recently (9.1.2023 or so).
I uninstalled the extension and re-installed the old 2.2.8 release from Github and now the Guidelines show again.

The right-click menu still worked (add, remove guidelines). But no guidelines were actually rendered.

Visual Studio installation info:

Microsoft Visual Studio Professional 2022
Version 17.1.0
VisualStudio.17.Release/17.1.0+32210.238
Microsoft .NET Framework
Version 4.8.03761

**Comment by pharring** [comment]
You're still on 17.1?
You might be hitting some variant of #87
Can you update Visual Studio to 17.4 or 17.5? Run the Visual Studio Installer and look for updates.

**Comment by blablubbabc** [comment]
Yeah, I am still on 17.1. I have seen the notes in the other ticket about 17.1, but since the previous version works fine for me, I guessed that this issue must be caused by something different (maybe related to the the net 7 sdk change, since there have been no other changes).

I am usually rather slow on updates since I don't want to accidentally break some part of my setup. I can let you know once I updated.

**Comment by pharring** [comment]
Well, there's a workaround for 17.1 listed in #87 you can try (uninstall the "Developer Analytics Tools").

**Comment by prlcutting** [comment]
I have been using this (awesome) extension in VS2022 for months with no problem (all versions up to the latest 17.4 version). For other reasons, I recently had to uninstall and reinstall Visual Studio. I'm now running version 17.5.1. I didn't get any errors during installation of the `EditorGuidelines.vsix`, and I see no errors in the IDE when using the extension, but the guidelines just won't render. Is there something I'm missing or need to do?

Here are a few things I've tried to troubleshoot the problem:

1. Most of my repos have the guidelines defined in an `.editorconfig` file. To rule that configuration out as a source of the problem, I tried creating a dummy project without an `.editorconfig`, but no dice.

1. I tried manually using the right mouse click menu to add a guideline, and I _think_ this "worked" (because if I try to add another at the same column, the menu item is grayed out, suggesting the extension knows there's already one there), but it never renders in the code editor.

1. Uninstall and reinstall the extension.

1. Uninstall and install version 2.2.8, but it wouldn't let me install that, because I think VS is newer than the extension supports.

1. I've tried changing the colors in the Fonts and Colors dialog for the guidelines, but no luck there either.

1. I confirmed that I have the "Developer Analytics Tool" installed, but that seemed like a solution to a problem specific to VS 17.1 anyway.

Is this maybe a 17.5.1 incompatibility?

Any help would be much appreciated. I can't live without this extension! :smile:

**Comment by blablubbabc** [comment]
> Yeah, I am still on 17.1. I have seen the notes in the other ticket about 17.1, but since the previous version works fine for me, I guessed that this issue must be caused by something different (maybe related to the the net 7 sdk change, since there have been no other changes).
> 
> I am usually rather slow on updates since I don't want to accidentally break some part of my setup. I can let you know once I updated.

Just as a quick follow-up on this: On a different environment I am currently using VisualStudio 17.4.2, .net 7 SDK, and EditorGuidelines 2.2.9 without problems.

**Comment by pharring** [comment]
🤷

**Comment by twojnarowski** [comment]
I am currently having the same issue as in https://github.com/pharring/EditorGuidelines/issues/87 on VS Comunity 17.8.5. I just installed VS on a new last week, the guidelines worked for a couple of days and then dissapeared. I have Developer Analytics Tools installed.

**Comment by pharring** [comment]
@twojnarowski are you still having problems? If so, could you open a new issue providing as much relevant information (such as the version of VS, the version of the extension and whether you're using .editorconfig?

**Comment by twojnarowski** [comment]
@pharring Well, actually no, I haven't changed anything, no new updates to VS or anything else, not even Windows updates and the guidelines are working correctly again... Sorry

**Comment by dgeelen-uipath** [comment]
Same here, what seemingly fixed it for me was uninstalling and re-installing the extension.
