### ISSUE TITLE
Not working in VS Enterprise 2022 17.10.0 Preview 1.0

### ISSUE THREAD

**Issue by bruno-brant** [pharring/EditorGuidelines#128]
Guidelines no longer show up in VS Enterprise 2022 17.10.0 Preview 1.0.

**Comment by ravindUwU** [comment]
Confirming that it doesn't work on Professional & Community 2022 `17.12.3` either 🤔.

**Comment by pharring** [comment]
@ravindUwU Can you describe the symptoms you're seeing?

**Comment by ravindUwU** [comment]
In my case, the symptom was just that the guidelines didn't show up in editors, with `guidelines = 100` included in the `.editorconfig`. 🤔 I recall re-opening the solution, and the `.editorconfig` file within the solution, and neither worked.

I say _was_ because, curiously, it seems to work now (as I opened Visual Studio to gather some screenshots for this comment)? 🤷 Thanks for investigating this issue! I'll post another comment if I notice it again 😓.

**Comment by ravindUwU** [comment]
Ohkay this is embarrassing. It turns out that I had, at some point, set the colour of my guidelines to white and they just weren't visible in light mode 🤣🤦.

The extension works just fine 😊.

<img src="https://github.com/user-attachments/assets/6cd1e1c0-c616-4bac-b836-391cfb2b56fa" height="250">

**Comment by pharring** [comment]
No worries, @ravindUwU 
I'm going to close this for now since the original report is old and it appears to be working now.
@bruno-brant, please re-open if you're still having trouble.
