### ISSUE TITLE
Additional styling options

### ISSUE THREAD

**Issue by NickVst** [pharring/EditorGuidelines#20]
I'd like to see more style options for styling the guideline, for example:

- Line style configurability (ability to pick between a solid line, a dashed line or a striped line)
- Line width configurability
- Line opacity configurability (could be faked, doing that by setting the color close to the background color)

I don't think it would be possible to implement this in the Options menu. It would probably require the configuration commands to be run from the command palette, or a different way to configure the guideline altogether.

**Comment by pharring** [comment]
I could see these being configured via .editorconfig
A more complex UI (a dedicated Tools/Options page) would obviously take longer.

**Comment by pharring** [comment]
I'm thinking we could have a `guidelines_style` setting in .editorconfig
The syntax would look and behave something like a CSS style for border:
```
guidelines_style = 1px dotted #FF0000;opacity:0.75
```

`1px` specifies the width in pixels.
`dotted` specifies the line style. Simple to support: solid, dotted and dashed
`#FF0000` is the color (RGB). I might be able to support named colors.
`opacity:0.75` specifies the alpha for the line (0.0 to 1.0)

For now, I'm not considering setting different styles for each guideline. But that could be added later by extending the syntax of the `guidelines` setting.

**Comment by pharring** [comment]
I've started working on this.

**Comment by pharring** [comment]
Note that `#` is not going to work for RGB values because it gets parsed as a comment in .editorconfig.
I think we can break with the CSS style and allow the opacity to be specified at the same time as the RGB.
WPF's ColorConverter can parse ARGB values with or without alpha as well as named color values.

Here are some valid styles:
- `guidelines_style = 1px dotted red`   Single pixel, red dotted line
- `guidelines_style = 1px dashed FF0000`    Single pixel, red dashed line (fully opaque)
- `guidelines style = 2px solid 80000000`    Two pixel, solid black line with 50% transparency

**Comment by pharring** [comment]
Fixed via #38
