### ISSUE TITLE
Release 2.2.5

### ISSUE THREAD

**Issue by pharring** [pharring/EditorGuidelines#62]
2.2.5 will be the final release for VS 2012 and 2013
It needs a bit of planning:

- [ ] Create a branch for legacy versions.
- [ ] Create a new VSIX identity for the legacy version.
- [ ] Update vsixmanifest for legacy version (install targets, URLs, readme, ?)
- [ ] Update Overview.md for legacy version
- [ ] Update Azure pipeline (to trigger on check-in to legacy branch) and to Release to the legacy VSIX
- [ ] Remove deprecation warning from legacy branch.
- [ ] Review telemetry code in legacy branch.
- [ ] Publish legacy version to marketplace.
- [ ] Update Overview.md in main branch with link to legacy version
- [ ] Publish 2.2.5 from main branch

**Comment by sharwell** [comment]
I believe you can package both the legacy and the new versions of the assembly in the same VSIX, and use the vsixmanifest to conditionally register the correct ones for the currently running version.

**Comment by pharring** [comment]
@sharwell I've never seen that done before. Do you have an example? Will it also work downlevel?

**Comment by sharwell** [comment]
Downlevel will ignore the version restriction, but it will also fail to load the newer assembly(ies) during MEF discovery because they reference new versions of the IDE assemblies that are not available downlevel. After failing to load the new assemblies, they will silently compose using only the older ones.

It's the `TargetVersion` attribute of the `Asset` element:
https://docs.microsoft.com/en-us/visualstudio/extensibility/vsix-extension-schema-2-0-reference?view=vs-2019#assets-element

**Comment by pharring** [comment]
2.2.5 has been released now (since there was a nice feature request which I implemented). It carries the "last version" warning for VS 2012 and 2013 users.

**Comment by pharring** [comment]
I'm going to revisit this now that I'm adding Dev 17 (VS 2022) support. Supposedly, the Marketplace handles multiple VSIXs.
